import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Next js - Learning',
    template: '%s | Learning'
  },
  description: 'Generated by Next.js',
}

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '1rem ', textAlign: 'center' }}>
          <p>Header Component</p>
        </header>
        {children}
        <footer style={{ backgroundColor: 'lightgray', padding: '1rem ', textAlign: 'center' }}>
          <p>Footer Component</p>
        </footer>
      </body>
    </html>
  )
}
